In [57]:
import pandas as pd
import yfinance
from tradingview_screener import Scanner, Query, Column
from datetime import datetime
from time import sleep

In [18]:
nrows, df = (Query()
 .select('close', 'volume', 'market_cap_basic', 'premarket_change')
 .where(
     Column('type') == 'stock',
     Column('is_primary') == True,
     Column('market_cap_basic') > 30e6,
     Column('premarket_change') > 3
 )
 .order_by('premarket_change', ascending=False)
 .get_scanner_data()
)
df

   ticker     close    volume  market_cap_basic  premarket_change
0     CCG    1.3300    936144      1.003361e+08         56.766917
1    BNAI    1.2700    118882      4.231888e+07         36.220472
2    SRDX   35.1000     42927      5.005260e+08         20.512821
3    ASTS    5.3300  10165643      1.372643e+09         18.574109
4    IKNA    1.3300   1526937      6.418329e+07         18.045113
5    BWAQ    8.6100     98383      4.772575e+07         16.144019
6    OOMA    7.9000    290328      2.087211e+08         15.189873
7    QBTS    1.4000   6791529      1.769329e+08         14.285714
8    AEON    1.3800    170701      5.398869e+07         13.043478
9    CHWY   16.9100  11230735      7.371239e+09         12.773507
10   AONC    2.3600     82068      7.862943e+07         12.288136
11    MRO   26.4500  15046987      1.491874e+10         10.964083
12   IMVT   28.4200    981099      4.129226e+09         10.837438
13   UBXG    6.1800     87014      1.668600e+08         10.194175
14   GNSS    1.7600    175988      7.848643e+07          9.727273
15   SNDX   20.0800    997728      1.706540e+09          9.224104
16   TELL    0.5608  19854357      4.689560e+08          9.004993
17     NB    2.2500    114705      8.281732e+07          8.000000
18   ZENV    3.0700     72297      8.313584e+07          7.817590
19    DKS  195.0000   2280820      1.595032e+10          7.692308
20   LANV    1.5000      2431      2.175322e+08          7.333333
21    RTC    0.9700     23458      8.506194e+07          7.216495
22   BCLI    0.5169    229009      3.622462e+07          7.196750
23    TCS    0.6720    235702      3.468311e+07          7.142857
24   OABI    4.1700    631012      4.904565e+08          7.098321
25   USAU    5.9050    208201      6.337410e+07          7.027942
26   FEAM    1.8400    257354      1.164459e+08          6.521739
27   SMLR   29.0000   1406079      2.049092e+08          6.034483
28    LEV    1.0200    148081      2.307419e+08          5.882353
29    PMN    1.5900     21820      3.014817e+07          5.660377
30    ANF  152.3900   2687146      7.786929e+09          5.638559
31   AMIX    2.0600     82499      3.871558e+07          5.339806
32   SATL    1.1400     29948      1.029465e+08          5.228070
33   VSTE    2.7300      1327      8.182766e+07          5.128205
34   BEAT    2.9400    363892      7.740735e+07          5.102041
35   ASXC    0.2350   1202189      6.399795e+07          4.978723
36   MNMD    8.3550    943128      5.890356e+08          4.967086
37   FRGE    1.6500    441976      2.987165e+08          4.848485
38   DGII   25.3400    209281      9.217323e+08          4.775059
39   SCLX    1.0800    549024      1.956851e+08          4.629630
40   NRDY    1.7600    808693      3.091908e+08          4.545455
41   KULR    0.3455   2727754      6.311498e+07          4.515195
42   PFIE    1.5200    230402      7.159387e+07          4.506579
43   SKYX    0.9523    465705      9.539039e+07          4.483881
44   MIST    1.6500    203422      8.787977e+07          4.242424
45   LFMD    7.7700    547028      3.285932e+08          4.118404
46   CGTX    2.2000    209675      8.812869e+07          4.090909
47   RCEL    8.6300    160123      2.226517e+08          3.939745
48    SDA    7.9400    217814      7.122582e+08          3.904282
49   TLNE  113.6000    887144      6.705680e+09          3.785211

In [19]:
for i, row in df.iterrows():
    ticker = yfinance.Ticker(row.ticker)
    print(f'================== {row.ticker} - {row.premarket_change :.2f}% ==================')
    for news in ticker.get_news():
        dt = datetime.fromtimestamp(news["providerPublishTime"])
        print('! ' * (dt.date() == datetime.today().date()) + f'[{dt}]', news['title'])
    print()

================== CCG - 56.77% ==================
[2024-05-24 08:00:00] Cheche Group Schedules First Quarter 2024 Earnings Release and Conference Call Date
[2024-05-13 09:00:00] Cheche Group Announces Partnership with Volkswagen (Anhui) Digital Sales and Services to Better Support Volkswagen Anhui's NEV Insurance Business
[2024-04-24 08:48:54] Cheche Group Inc.'s (NASDAQ:CCG) largest shareholder, CEO Lei Zhang sees holdings value fall by 15% following recent drop
[2024-03-28 16:30:00] Cheche Group Announces Partnership with the Insurance Brokerage Firm in Xiaomi Group
[2024-03-28 06:00:00] Cheche Group Reports Fourth Quarter and Full Year 2023 Unaudited Financial Results
[2024-03-27 09:00:00] Cheche CEO Lei Zhang Highlights the Strategic High Ground of Car Insurance for Auto Makers at China EV100
[2024-03-21 09:00:00] Cheche Group Schedules Fourth Quarter and Full Year 2023 Earnings Release and Conference Call Date
[2024-03-05 09:00:00] Cheche Group Expands Partnership with Sinopec to Deliver Digital Insurance Solutions to Retail Network

================== BNAI - 36.22% ==================
[2024-05-14 16:15:00] BEN Reports First Quarter 2024 Financial Results
[2024-05-09 08:00:00] BEN Achieves HIPAA Compliance for Healthcare AI Assistants
[2024-05-02 09:27:00] BEN Announces Date of First Quarter 2024 Financial Results Conference Call
[2024-04-16 08:00:00] BEN Partners with OSF HealthCare to Develop AI Solution for Primary Care Training & Patient Evaluation
[2024-04-09 12:06:00] Provana and BEN Sign Partnership to Revolutionize Business Process Management with AI Integration
[2024-03-14 18:48:00] BEN Announces Closing of Business Combination, to Begin Trading on Nasdaq Under Symbol "BNAI"

================== SRDX - 20.51% ==================
! [2024-05-29 07:00:00] Surmodics Enters into Definitive Agreement to be Acquired by GTCR for $43.00 Per Share in Cash, Representing an Approximate Equity Value of $627 Million
[2024-05-21 11:33:17] Surmodics, Inc.'s (NASDAQ:SRDX) Intrinsic Value Is Potentially 96% Above Its Share Price
[2024-05-20 10:49:00] Here's Why You Should Hold Surmodics (SRDX) Stock for Now
[2024-05-04 09:59:22] Surmodics, Inc. Just Beat Earnings Expectations: Here's What Analysts Think Will Happen Next
[2024-05-03 13:12:00] Surmodics (SRDX) Q2 Earnings Top Estimates, '24 View Up
[2024-05-02 03:01:21] Surmodics Inc (SRDX) Q2 2024 Earnings Call Transcript Highlights: Robust Revenue Growth and ...
[2024-05-01 14:05:13] Top Midday Gainers
[2024-05-01 09:30:23] SurModics (SRDX) Q2 Earnings: How Key Metrics Compare to Wall Street Estimates

================== ASTS - 18.57% ==================
! [2024-05-29 07:30:00] AST SpaceMobile and Verizon Announce Plans to Target 100 Percent Geographical Coverage of the Continental United States from Space on Premium 850 MHz Cellular Spectrum
[2024-05-15 16:15:00] AST SpaceMobile Provides Business Update and First Quarter 2024 Results
[2024-05-15 16:10:00] AT&T and AST SpaceMobile Announce Definitive Commercial Agreement
[2024-05-06 17:09:00] AST SpaceMobile Welcomes Andrew Johnson as New Chief Legal Officer
[2024-04-29 17:00:00] AST SpaceMobile to Provide Quarterly Business Update on May 15, 2024
[2024-04-01 16:30:00] AST SpaceMobile Provides Business Update and Fourth Quarter and Full Year 2023 Results
[2024-03-27 17:46:00] AST SpaceMobile ASIC Chip Enters Tape-Out Phase in Collaboration with TSMC
[2024-03-20 18:30:00] AST SpaceMobile to Provide Quarterly Business Update on April 1, 2024

================== IKNA - 18.05% ==================
[2024-05-28 17:07:39] Ikena Oncology to Cut Jobs, Explore Options, End IK-930 Program; Shares Rise After Hours
[2024-05-28 16:42:00] UPDATE – Ikena Oncology Announces Strategic Update
[2024-05-28 16:15:00] Ikena Oncology Announces Strategic Update
[2024-05-13 16:45:00] Ikena Oncology Reports First Quarter 2024 Financial Results and Corporate Update
[2024-04-10 08:00:00] Ikena Oncology to Present at the Stifel 2024 Virtual Targeted Oncology Forum
[2024-03-14 07:50:28] Ikena Oncology Full Year 2023 Earnings: EPS Beats Expectations, Revenues Lag
[2024-03-12 08:00:00] Ikena Oncology Reports Fourth Quarter and Full Year 2023 Financial Results

================== BWAQ - 16.14% ==================
[2024-05-16 08:35:00] Blue World Acquisition Corporation Announces the Redemption Deadline as May 23, 2024 for the Extraordinary General Meeting to Approve the Business Combination with TOYO Solar
[2024-05-03 06:10:00] Blue World Acquisition Corporation Announces Extension of the Deadline for an Initial Business Combination
[2024-04-15 08:07:00] Blue World Acquisition Corporation Postponed the Extraordinary General Meeting  to Approve the Business Combination with TOYO Solar Pending  A Post-Effective Amendment to The Registration Statement

================== OOMA - 15.19% ==================
[2024-05-28 17:25:02] Ooma (OOMA) Q1 Earnings and Revenues Surpass Estimates
[2024-05-28 16:26:04] Ooma: Fiscal Q1 Earnings Snapshot
[2024-05-28 16:15:00] Ooma Reports Fiscal First Quarter 2025 Financial Results
[2024-05-22 08:18:43] Ooma (NYSE:OOMA) shareholders have endured a 54% loss from investing in the stock three years ago
[2024-05-15 16:15:00] Ooma to Attend the 44th Annual William Blair Growth Stock Conference
[2024-05-08 19:05:03] Airgain (AIRG) Reports Q1 Loss, Tops Revenue Estimates
[2024-05-08 16:15:00] Ooma Schedules Release of First Quarter Fiscal 2025 Results
[2024-05-07 17:15:04] Arista Networks (ANET) Tops Q1 Earnings and Revenue Estimates

================== QBTS - 14.29% ==================
[2024-05-28 07:00:00] D-Wave Quantum Set to Join Russell 3000® Index
[2024-05-20 07:00:00] D-Wave CEO Urges Leaders to Embrace an AI and Quantum Future Now in New Forbes Technology Council Column
[2024-05-15 07:00:00] D-Wave to Present at Reuters Supply Chain USA 2024
[2024-05-13 07:00:00] D-Wave and the University of Southern California Renew Multiyear Agreement to Advance Annealing Quantum Computing Research and Adoption
[2024-05-13 07:00:00] D-Wave Reports First Quarter 2024 Results
[2024-05-08 07:00:00] D-Wave to Showcase Quantum Computing Advancements at 19th Annual Needham Technology, Media and Consumer Conference
[2024-04-29 07:00:00] D-Wave Quantum Inc. Announces Date for First Quarter Fiscal Year 2024 Earnings Call
[2024-04-26 09:35:06] After Plunging -27.45% in 4 Weeks, Here's Why the Trend Might Reverse for D-WAVE QUANTUM (QBTS)

================== AEON - 13.04% ==================
! [2024-05-29 08:00:00] AEON Biopharma Announces Strategic Resource Reprioritization and Cost Reduction Plan
[2024-05-14 16:05:00] AEON Biopharma Reports First Quarter 2024 Financial Results
[2024-05-09 09:35:05] AEON Biopharma, Inc. (AEON) Loses -79.2% in 4 Weeks, Here's Why a Trend Reversal May be Around the Corner
[2024-05-09 08:00:00] AEON Biopharma Provides Update on Development Pipeline
[2024-05-03 16:08:03] US Equity Markets Close Higher Friday Following Weak Jobs Report
[2024-05-03 15:55:16] Sector Update: Health Care Stocks Mixed Late Afternoon
[2024-05-03 14:37:35] Top Midday Decliners
[2024-05-03 09:05:21] Sector Update: Health Care Stocks Mixed Pre-Bell Friday

================== CHWY - 12.77% ==================
! [2024-05-29 07:13:52] Chewy: Fiscal Q1 Earnings Snapshot
! [2024-05-29 07:05:00] Chewy Announces First Quarter 2024 Financial Results
[2024-05-27 09:30:10] Wall Street Bulls Look Optimistic About Chewy (CHWY): Should You Buy?
[2024-05-24 17:45:11] Chewy (CHWY) Laps the Stock Market: Here's Why
[2024-05-24 11:10:40] Chewy Fiscal Q1 Sales Likely Poised for 'Modest' Upside, Wedbush Says
[2024-05-23 09:55:07] Wall Street Analysts Believe Chewy (CHWY) Could Rally 45.85%: Here's is How to Trade
[2024-05-20 17:50:05] Chewy (CHWY) Surpasses Market Returns: Some Facts Worth Knowing
[2024-05-17 05:10:00] Have $500? 2 Unstoppable Growth Stocks to Buy Without Hesitation in the New Bull Market

================== AONC - 12.29% ==================
[2024-05-21 06:00:00] American Oncology Network Announces Voluntary Delisting From Nasdaq
[2024-05-16 16:30:00] American Oncology Network Appoints New Board Member
[2024-05-15 16:47:00] American Oncology Network, Inc. Announces First Quarter 2024 Financial Results
[2024-05-15 08:00:00] American Oncology Network Advances Karyogram Segmentation and Increases the Speed to Results with New A.I. Software
[2024-05-14 08:10:00] American Oncology Network Announces Date Change for First Quarter 2024 Earnings Release Date and Conference Call
[2024-05-03 17:30:00] American Oncology Network Announces CFO Transition
[2024-04-30 08:00:00] American Oncology Network Announces First Quarter 2024 Earnings Release Date and Conference Call
[2024-04-25 08:00:00] American Oncology Cares Foundation Expands Non-Medical Financial Support to Local Cancer Patients in Indiana and Nevada

================== MRO - 10.96% ==================
! [2024-05-29 06:11:15] ConocoPhillips in Talks to Acquire Marathon Oil, FT Reports
! [2024-05-29 06:07:59] Oil Extends Gain as Geopolitical Risks Simmer Before OPEC+ Talks
! [2024-05-29 06:05:51] ConocoPhillips in advanced discussions to purchase Marathon Oil
! [2024-05-29 05:01:38] Marathon Oil Stock Climbs on Report It Could Be Bought by ConocoPhillips
! [2024-05-29 02:20:45] ConocoPhillips in advanced talks to buy Marathon Oil, FT reports
[2024-05-23 12:38:14] The Return Trends At Marathon Oil (NYSE:MRO) Look Promising
[2024-05-14 12:02:00] Top Research Reports for Union Pacific, Freeport-McMoRan & Block
[2024-05-14 12:00:09] All You Need to Know About Marathon Oil (MRO) Rating Upgrade to Buy

================== IMVT - 10.84% ==================
[2024-05-24 16:23:19] Immunovant Insider Sold Shares Worth $479,233, According to a Recent SEC Filing
[2024-05-13 09:55:10] Wall Street Analysts Think Immunovant (IMVT) Could Surge 68.63%: Read This Before Placing a Bet
[2024-05-07 06:40:00] Zacks Industry Outlook Highlights BioMarin, Blueprint  Medicines, Immunovant, Kymera and Ligand
[2024-05-06 09:50:00] 5 Biotech Stocks Worth Adding to Your Portfolio in 2024
[2024-04-24 07:39:37] Should You Hold Immunovant (IMVT)?
[2024-04-22 11:53:00] Here's Why You Should Add Immunovant (IMVT) to Your Portfolio
[2024-04-17 12:00:11] What Makes Immunovant (IMVT) a New Buy Stock
[2024-03-25 15:00:00] Wall Street’s Favorite Biotech Stocks? 3 Names That Could Make You Filthy Rich

================== UBXG - 10.19% ==================
[2024-04-01 16:05:00] U-BX Technology Ltd. Announces Closing of $10 Million Initial Public Offering
[2024-03-27 17:00:00] U-BX Technology Ltd. Announces Pricing of $10Million Initial Public Offering
[2024-03-26 14:37:48] Boasting A 19% Return On Equity, Is U-BX Technology Ltd. (NASDAQ:UBXG) A Top Quality Stock?

================== GNSS - 9.73% ==================
[2024-05-23 08:00:00] Genasys to Present at MicroCap Rodeo Conference
[2024-05-23 07:36:20] Analysts Just Shaved Their Genasys Inc. (NASDAQ:GNSS) Forecasts Dramatically
[2024-05-21 16:30:00] Genasys Announces Director Resignation Due to New Employment Requirements
[2024-05-15 08:30:00] Genasys Receives $2.7 Million U.S. Navy Order for LRAD Maritime Systems
[2024-05-15 03:08:21] Genasys Inc (GNSS) Q2 2024 Earnings Call Transcript Highlights: Diving Into Financials and ...
[2024-05-14 16:14:00] Genasys Inc. Reports Fiscal Second Quarter 2024 Financial Results
[2024-05-14 16:14:00] Genasys Announces $15 Million Two-Year Term Loan Agreement
[2024-05-14 16:14:00] Genasys Announces Expansion of Its Board of Directors

================== SNDX - 9.22% ==================
[2024-05-15 16:05:00] Syndax Pharmaceuticals Appoints Aleksandra Rizo, M.D., Ph.D. to the Board of Directors
[2024-05-12 08:26:17] Syndax Pharmaceuticals, Inc. (NASDAQ:SNDX) Q1 2024 Earnings Call Transcript
[2024-05-09 07:00:00] Syndax Announces Participation at the Bank of America Securities 2024 Health Care Conference
[2024-05-09 03:03:17] Syndax Pharmaceuticals Inc (SNDX) Q1 2024 Earnings Call Transcript Highlights: Strategic ...
[2024-05-08 09:22:50] Syndax Pharmaceuticals Q1 Net Loss Widens
[2024-05-08 07:27:37] Syndax: Q1 Earnings Snapshot
[2024-05-08 07:06:00] Syndax Pharmaceuticals Reports First Quarter 2024 Financial Results and Provides Clinical and Business Update
[2024-05-03 16:05:00] Syndax Pharmaceuticals Reports Inducement Grants Under NASDAQ Listing Rule 5635(c)(4)

================== TELL - 9.00% ==================
! [2024-05-29 07:00:00] Aethon Energy to Acquire Tellurian Integrated Upstream Assets
[2024-05-28 09:55:04] Tellurian (TELL) Forms 'Hammer Chart Pattern': Time for Bottom Fishing?
[2024-05-02 08:57:26] Tellurian Inc (TELL) Reports Q1 2024 Earnings: Misses Analyst Revenue and Earnings Forecasts
[2024-05-02 07:33:00] Tellurian reports first quarter 2024 results and Driftwood LNG progress
[2024-03-18 06:00:00] Tellurian Makes Leadership Changes

================== NB - 8.00% ==================
[2024-05-23 16:35:00] NioCorp Engages J.P. Morgan to Assist with EXIM Financing of Elk Creek Critical Minerals Project
[2024-05-20 16:01:00] Study Finds Electrifying NioCorp's Critical Minerals Mine Could Lead to Faster Time to Full Production Plus Significant Economic and Environmental Gains
[2024-05-06 17:13:00] NioCorp Receives Preliminary Indicative Term Sheet from U.S. Export-Import Bank on Potential $800 Million Debt Financing
[2024-05-01 08:50:00] NioCorp to Voluntarily Delist from the Toronto Stock Exchange as of Close of Markets on May 3, 2024
[2024-04-18 07:00:00] NioCorp Plans to Investigate Feasibility of Rare Earth Permanent Magnet Recycling
[2024-04-17 07:00:00] NioCorp to Voluntarily Delist from the TSX in Favor of its Current Nasdaq Listing
[2024-04-12 09:20:00] NioCorp Announces Closing of Financing Agreement
[2024-03-14 17:30:00] NioCorp Completes Issuance and Sale of 85,000 Shares under the Standby Equity Purchase Agreement

================== ZENV - 7.82% ==================
[2024-05-21 07:49:56] Top Premarket Decliners
[2024-05-15 07:00:00] Zenvia Files its Annual Report on Form 20-F for Fiscal Year 2023
[2024-05-03 07:00:00] 3 Little-Known Stocks That Could Make You Rich by 2029
[2024-04-28 10:46:16] 38% of Zenvia Inc. (NASDAQ:ZENV) is owned by insiders, and they've been buying recently
[2024-04-20 06:00:00] Hidden Titans: 3 Stocks Ready to Outperform in the Next Earnings Season
[2024-04-15 08:50:00] ZENVIA sets agenda for fiscal fourth quarter and full year results
[2024-04-09 08:00:00] Secret Millionaires: 3 Underpriced Stocks to Skyrocket Your Wealth
[2024-04-04 08:38:00] Millionaire Blueprint: 3 Game-Changing Stocks You Can’t Ignore

================== DKS - 7.69% ==================
! [2024-05-29 07:08:03] Dick's: Fiscal Q1 Earnings Snapshot
! [2024-05-29 07:00:00] DICK'S Sporting Goods Reports First Quarter Results; Raises 2024 Outlook
[2024-05-28 10:15:00] The DICK'S Sporting Goods Foundation Quarterly Giving Series: Q1 2024
[2024-05-28 03:00:54] Dick's (DKS) Q1 Earnings: What To Expect
[2024-05-27 11:02:00] Here's How DICK'S Sporting (DKS) Looks Ahead of Q1 Earnings
[2024-05-24 18:00:07] Dick's Sporting Goods (DKS) Exceeds Market Returns: Some Facts to Consider
[2024-05-24 12:27:49] This week: Consumer confidence, Dick's Sporting Goods earnings and the latest US inflation reading
[2024-05-24 10:29:00] Shoe Carnival (SCVL) Q1 Earnings Beat Estimates, Sales Up Y/Y

================== LANV - 7.33% ==================
[2024-05-02 07:36:22] Lanvin Group Holdings Reports Full Year 2023 Earnings
[2024-04-30 06:00:00] Lanvin Group Shows Resiliency in Sales and On-Track Margin Improvement in 2023
[2024-04-22 06:00:00] Lanvin Group to Report 2023 Full-Year Audited Results on April 30, 2024

================== RTC - 7.22% ==================
[2024-03-18 08:15:00] Baijiayun Group Ltd Announces Receipt of Nasdaq Notice

================== BCLI - 7.20% ==================
[2024-05-20 06:00:00] BrainStorm Cell Therapeutics to Present New Biomarker Data Suggesting ALS Patients May Benefit From Longer-Term Treatment with NurOwn
[2024-05-14 16:30:00] BrainStorm Cell Therapeutics Announces First Quarter 2024 Financial Results and Provides Corporate Update
[2024-04-16 18:30:00] BrainStorm Cell Therapeutics Announces Management Changes as Company Plans Registrational Phase 3b Trial of NurOwn
[2024-04-11 06:27:00] BCLI: Receives SPA Agreement from FDA on Design of Phase 3b Trial of NurOwn™…
[2024-04-11 06:00:00] BrainStorm Cell Therapeutics Regains Compliance with NASDAQ Minimum Market Value Rule
[2024-04-10 06:00:00] BrainStorm Cell Therapeutics Announces Peer-reviewed Publication of Biomarker Data from NurOwn's® Phase 3 Clinical Trial in ALS
[2024-04-09 06:00:00] BrainStorm Cell Therapeutics Announces Agreement with FDA on a Special Protocol Assessment (SPA) for Phase 3b Trial in ALS
[2024-04-08 06:00:00] BrainStorm Cell Therapeutics to Provide Update on NurOwn Program

================== TCS - 7.14% ==================
[2024-05-15 03:48:41] Q4 2023 Container Store Group Inc Earnings Call
[2024-05-15 03:00:58] The Container Store Group Inc (TCS) (Q4 2023) Earnings Call Transcript Highlights: Navigating ...
[2024-05-14 08:25:00] The Container Store faces delisting as Q4 sales plunge
[2024-05-14 07:55:02] Container Store Group (TCS) Reports Q4 Loss, Tops Revenue Estimates
[2024-05-14 07:02:47] Container Store: Fiscal Q4 Earnings Snapshot
[2024-05-14 06:46:00] The Container Store Group, Inc. Announces Fourth Quarter and Full Fiscal Year 2023 Financial Results
[2024-05-14 06:45:00] The Container Store Receives Notice of Non-Compliance with New York Stock Exchange Trading Share Price Listing Rule
[2024-05-08 16:05:00] The Container Store Group, Inc. Announces Fourth Quarter and Full Fiscal 2023 Earnings Conference Call

================== OABI - 7.10% ==================
! [2024-05-29 06:15:48] Daily – Vickers Top Buyers & Sellers for 05/29/2024
[2024-05-28 18:01:46] Omniab Insider Bought Shares Worth $1,059,840, According to a Recent SEC Filing
[2024-05-20 08:05:00] OmniAb to Participate in the Jefferies Global Healthcare Conference
[2024-05-15 16:05:00] OmniAb Presents High-Throughput Single B-cell Screening xPloration® Data at the 20th Annual PEGS Boston Summit
[2024-05-12 08:56:46] OmniAb, Inc. (NASDAQ:OABI) Q1 2024 Earnings Call Transcript
[2024-05-11 08:17:31] We're Keeping An Eye On OmniAb's (NASDAQ:OABI) Cash Burn Rate
[2024-05-11 08:09:08] OmniAb First Quarter 2024 Earnings: Misses Expectations
[2024-05-09 16:05:00] OmniAb Reports First Quarter 2024 Financial Results and Business Highlights

================== USAU - 7.03% ==================
[2024-05-09 08:15:00] U.S. Gold Corp Chairman Explains How His Gold and Copper Assets Can Exploit A Current Storm Of 2024 Opportunity
[2024-05-08 07:30:00] U.S. Gold Corp. Announces Mine Operating Permit Approval for the CK Gold Project in Wyoming
[2024-05-02 08:47:00] U.S. Gold Corp. to Present at SME's 9th Current Trends in Mining Finance Conference in New York
[2024-04-29 08:47:00] U.S. Gold Corp. Announces Results of its 2023 Annual General Meeting of Shareholders
[2024-04-25 08:47:00] U.S. Gold Corp. Closes $4.9 Million Non-Brokered Registered Direct Offering
[2024-04-24 09:35:48] Latest Insider Trading Activity: 11 Stocks Executives and Directors are Buying
[2024-04-23 08:47:00] U.S. Gold Corp. Annual General Meeting (AGM) Being Held on April 26, 2024
[2024-04-15 08:30:00] U.S. GOLD CORP. ANNOUNCES $4.9 MILLION REGISTERED DIRECT OFFERING

================== FEAM - 6.52% ==================
[2024-05-28 09:00:00] 5E Advanced Materials Announces Agreement to Sell $6 Million of Additional Convertible Notes
[2024-05-22 12:00:00] VIDEO - CEO Clips - 5E Advanced Materials: A New Chapter in Boron and Lithium Production
[2024-04-29 08:10:00] 5E Advanced Materials Announces First Boric Acid Production and Extended Waiver of Cash Covenant
[2024-04-02 18:51:00] 5E Advanced Materials Commences Commercial Production At 5E Boron Americas Complex

# DAY

In [79]:
nrows, df = (Query().
    select('close', 'change|5', 'change_abs|5', 'market_cap_basic', 'Value.Traded|5', 'sector').
    where(
        Column('type') == 'stock',
        Column('is_primary') == True,
        Column('exchange').isin(['NASDAQ', 'NYSE']),
        Column('change|5') < -1,
        #Column('Value.Traded|5') > 0.5e6,
        Column('market_cap_basic') > 30e6
    ).
    order_by('change|5', ascending=True).
    get_scanner_data()
)
df

,ticker,close,change|5,change_abs|5,market_cap_basic,Value.Traded|5,sector
0,PTWO,13.14000,-5.467626,-0.760000,6.854208e+07,5256.00000,Finance
1,XLO,0.89200,-4.836382,-0.045333,3.292584e+07,892.00000,Health Technology
2,PEGR,8.57000,-4.671858,-0.420000,1.497502e+08,857.00000,Finance
3,ZBAO,4.03000,-4.045334,-0.169900,3.538193e+07,403.00000,Finance
4,STCN,11.15000,-4.012534,-0.466100,7.008433e+07,5575.00000,Commercial Services
5,LSB,0.96000,-3.990399,-0.039900,1.807948e+08,8544.00000,Health Technology
6,VABK,29.01000,-3.781095,-1.140000,1.558102e+08,2901.00000,Finance
7,SUGP,2.34000,-3.703704,-0.090000,3.100500e+07,936.00000,Commercial Services
8,LGCB,2.79000,-3.463548,-0.100100,5.998500e+07,279.00000,Technology Services
9,AUID,7.63000,-3.295311,-0.260000,7.210518e+07,763.00000,Electronic Technology
10,SHMD,4.50000,-3.257014,-0.151500,1.988445e+08,1350.00000,Finance
11,CJET,0.43500,-3.225806,-0.014500,6.990762e+07,435.00000,Consumer Durables
12,DXR,9.22500,-3.058008,-0.291000,4.368026e+07,1125.45000,Miscellaneous
13,CETY,1.30000,-2.985075,-0.040000,5.580867e+07,18132.40000,Producer Manufacturing
14,OSS,2.30000,-2.953586,-0.070000,4.810862e+07,7820.00000,Electronic Technology
15,HUDA,10.95000,-2.925532,-0.330000,4.927667e+07,1095.00000,Finance
16,SWVL,10.11700,-2.917186,-0.304000,9.251341e+07,12140.40000,Transportation
17,VYNE,2.50000,-2.912621,-0.075000,3.632062e+07,14520.00000,Health Technology
18,ATLO,19.85000,-2.886497,-0.590000,1.784945e+08,33745.00000,Finance
19,SIEB,2.07000,-2.816901,-0.060000,8.255353e+07,207.00000,Finance
20,NPAB,11.96000,-2.764228,-0.340000,8.291298e+07,2392.00000,Finance
21,ECX,1.12000,-2.676399,-0.030800,3.786353e+08,224.00000,Technology Services
22,TBNK,7.75350,-2.655367,-0.211500,6.848074e+07,775.35000,Finance
23,OCX,2.58000,-2.641509,-0.070000,3.448076e+07,258.00000,Health Technology
24,DHAC,13.05500,-2.574627,-0.345000,4.704978e+07,2519.61500,Finance
25,GROV,1.54000,-2.531646,-0.040000,5.880034e+07,32036.62000,Consumer Non-Durables
26,XGN,1.92000,-2.453894,-0.048300,3.335708e+07,192.00000,Health Services
27,LVRO,5.80000,-2.356902,-0.140000,6.588932e+08,1160.00000,Distribution Services
28,CDTG,3.81000,-2.307692,-0.090000,4.076700e+07,381.00000,Industrial Services
29,CAPT,5.12000,-2.290076,-0.120000,1.483767e+08,7352.32000,Producer Manufacturing
30,UG,9.15000,-2.287435,-0.214200,4.203510e+07,18300.00000,Process Industries
31,QMCO,0.42900,-2.277904,-0.010000,4.077242e+07,214.50000,Electronic Technology
32,INKT,0.93140,-2.204956,-0.021000,3.234533e+07,93.14000,Health Technology
33,EPIX,6.29000,-2.177294,-0.140000,2.790432e+08,629.00000,Health Technology
34,ORGN,1.12120,-2.173913,-0.025000,1.648413e+08,48398.62500,Process Industries
35,ARL,13.02000,-2.095694,-0.278700,2.102996e+08,5377.26000,Finance
36,DJCO,375.01000,-2.093831,-8.020000,5.163985e+08,75002.00000,Consumer Services
37,QBTS,1.44500,-2.047782,-0.030000,1.826201e+08,102361.42000,Electronic Technology
38,QLI,0.84345,-1.985962,-0.017090,3.015334e+07,84.34500,Health Technology
39,FSBW,32.00000,-1.975800,-0.645000,2.494735e+08,3200.00000,Finance
40,PFIE,1.51000,-1.948052,-0.030000,7.112286e+07,9664.00000,Electronic Technology
41,ALGS,0.60114,-1.934747,-0.011860,4.695500e+07,3421.08774,Health Technology
42,FEXD,11.22000,-1.923077,-0.220000,7.682337e+07,2019.60000,Finance
43,AQMS,0.39260,-1.825456,-0.007300,5.132303e+07,4201.60520,Non-Energy Minerals
44,MOVE,0.38510,-1.785259,-0.007000,3.784188e+07,2306.36390,Technology Services
45,PLBY,0.88400,-1.766863,-0.015900,6.436236e+07,106.08000,Consumer Services
46,LARK,19.17000,-1.691804,-0.329900,1.049340e+08,14933.43000,Finance
47,PRE,5.86050,-1.669463,-0.099500,7.159905e+07,1172.10000,Finance
48,PASG,1.19000,-1.652893,-0.020000,7.335232e+07,119.00000,Health Technology
49,MOBX,2.19000,-1.626089,-0.036200,5.954110e+07,14217.48000,Electronic Technology